### PR TITLE
cpu/pic32: Prepare for upcoming pic32 platform and cleanup

### PR DESCRIPTION
**Pull request by Avinash95**
This connects #62

### CODE REVIEW

**Comment by mtusnio** [comment]
The PR message should be changed to present tense, as in "add support for (...)".

The permissions for the files change, is that alright?

**Comment by ghost** [comment]
@mtusnio About the PR message, it should be more like "Prepare for upcoming pic32 platform and cleanup"

@Avinash95 Did you try building for seedeye since one commit changes the Makefile ?

**Comment by Avinash95** [comment]
@francois-berder-imgtec I tried building it for seedeye, and its building successfully.

**Comment by Avinash95** [comment]
@mtusnio no it was not alright, removed the execute permission

**Comment by mtusnio** [comment]
+1 Looks good to me. I guess we can close this once we open up a PR to upstream?

**Review by mtusnio — APPROVED** [review]

**Pull request merged**
